For 82
forter/forter-magento2 pull request #37
Opened 2021-01-21 07:59 UTC by pniel-cohen

2021-01-21 20:14 UTC, erezkoren commented on view/frontend/templates/forter.phtml
> +      if(value.length === 16){
credit cards can be between 13-19 digits included

2021-01-21 20:16 UTC, erezkoren commented on view/frontend/templates/forter.phtml
> +        xhr.open("POST", '/forter/index/sessions', true);
this endpoint should not be related to forter --> it is better to change it to cardDetails endpoint or something similar.
we want the customer/developer will think the merchant is collecting the info of the bin+last4 and not the merchant

2021-01-21 20:17 UTC, erezkoren commented on view/frontend/templates/forter.phtml
> +    <?php if ($preAuthIsActive && strlen($elementToObserve) > 1): ?>
it is not necessarily related to pre-auth, we can use the bin+last4 also in postAuth

2021-01-21 20:19 UTC, erezkoren commented on etc/adminhtml/system.xml
> +                    <label>Advanced Settings Pre Auth</label>
it is not necessarily only in preauth, we want the capability and data also in the postauth

2021-01-26 05:54 UTC, orpolaczek commented on Block/Forter.php
> +    public function getPreAuthIsActive()
not super critical, but usually this method would be called `isPreAuthActive`
If it's a must to have `get` before it, then `getIsPreAuthActive` :) 

Just makes the code more readable, and when I see `getIs........` in an if clause I know immediately it's a boolean

2021-01-26 05:55 UTC, orpolaczek commented on Controller/Index/Sessions.php
> +            $forterToken = $this->getRequest()->getHeader('Forter-Token');
@zachGirit - IIRC we already added it. where did it go?

2021-01-26 05:57 UTC, orpolaczek commented on Model/RequestBuilder/BasicInfo.php
> +        $forterToken = $this->customerSession->getForterToken() ? $this->customerSession->getForterToken() : $this->cookieManager->getCookie("forterToken");
same here. we already added this stuff here: https://github.com/forter/forter-magento2/pull/36/files 
what's going on? 

Can you rebase?

2021-01-26 05:59 UTC, orpolaczek commented on view/frontend/templates/forter.phtml
> +  xhr.setRequestHeader("Forter-Token", evt.detail);
same. we added this before.

2021-01-26 06:00 UTC, orpolaczek commented on view/frontend/templates/forter.phtml
> +    <?php if ($preAuthIsActive && strlen($elementToObserve) > 1): ?>
+1

2021-01-26 06:02 UTC, orpolaczek commented on view/frontend/templates/forter.phtml
> +      value = $(this).val();
```suggestion
      value = $(this).val() || '';
```

so you won't crash on .substr

2021-01-26 06:04 UTC, orpolaczek requested changes
please see my comments

2021-02-02 13:07 UTC, orpolaczek approved these changes

2021-02-02 13:07 UTC, merged

2021-02-03 14:55 UTC, erezkoren commented on etc/adminhtml/system.xml
> +                      <label>Class or Id identifer for the Listener</label>
identifer typo --> `identifier` @pniel-cohen @zachGirit

2021-02-03 14:56 UTC, erezkoren commented on etc/adminhtml/system.xml
> +                          Please add the class or ID of the input of the CC you want to observe.
can you add real example

2021-02-03 15:06 UTC, erezkoren commented on view/frontend/templates/forter.phtml
>    $(function () {
@pniel-cohen @zachGirit we need to remove the dependency on jQuery, some merchants not supporting it