2.0.26
forter/forter-magento2 pull request #47
Opened 2021-02-28 07:51 UTC by pniel-cohen

* Fixed issue on cc listener (FOR-91).
* New Logger.

2021-03-03 20:14 UTC, orpolaczek commented on Logger/Handler/ErrorHandler.php
> +    protected $fileName = '/var/log/Forter/exception.log';
that's not OS safe. 
perhaps worth either piggy-backing existing log dir (`pathinfo(ini_get('error_log'),PATHINFO_DIRNAME);`?) or allowing the user to configure this.

2021-03-03 20:20 UTC, orpolaczek requested changes

2021-03-03 20:20 UTC, orpolaczek commented on Logger/Handler/ResponseHandler.php
> +    protected $fileName = '/var/log/Forter/response.log';
same as above

2021-03-03 20:20 UTC, orpolaczek commented on view/frontend/templates/forter.phtml
> +                $(document).on('change', '<?php echo $elementToObserve; ?>', function(event) {
this reverts a feature Erez from our end requested for, explicitly

2021-03-03 20:20 UTC, orpolaczek commented on Model/AbstractApi.php
> +        $this->forterResponseLogger = $forterResponseLogger;
why two loggers and not just one with different log levels? 
Another thing - you will be logging **every API request body**
That log file will inflate.

I don't see a log strategy specified here for Monolog, so what are the defaults of it? 
If there's no default - the log files will get to a huge size and might cause our merchant to run out of disk space on the log volume / just create noise for them.

2021-03-22 13:37 UTC, pniel-cohen commented on Logger/Handler/ErrorHandler.php
> +    protected $fileName = '/var/log/Forter/exception.log';
That's the standard way to do that on Magento 2 modules (even the original ones).

2021-03-22 13:37 UTC, pniel-cohen commented on Logger/Handler/ResponseHandler.php
> +    protected $fileName = '/var/log/Forter/response.log';
That's the standard way to do that on Magento 2 modules (even the original ones).

2021-03-22 13:42 UTC, pniel-cohen commented on view/frontend/templates/forter.phtml
> +                $(document).on('change', '<?php echo $elementToObserve; ?>', function(event) {
I had to remove that because it caused issues regarding the last4digits. Reverting back to jQuery solved it.

2021-03-25 09:24 UTC, orpolaczek commented on Model/AbstractApi.php
> +        $this->forterResponseLogger = $forterResponseLogger;
@pniel-cohen  that still waits for your response :)

2021-03-25 09:25 UTC, orpolaczek commented on view/frontend/templates/forter.phtml
> +                $(document).on('change', '<?php echo $elementToObserve; ?>', function(event) {
@pniel-cohen  it's not a good answer. We need to make it work **with** query selectors, and **without jQuery**. 
with that being said - it can wait for the next version :)

2021-03-25 12:56 UTC, merged

2021-03-29 12:22 UTC, zach1988 commented on Model/AbstractApi.php
> +        $this->forterResponseLogger = $forterResponseLogger;
@orpolaczek 
1. there are two logs because this was the request one file for errors and one handler for request & response. I also think it's better but we can easily combine them and use the **info** tag for request & response and **error** for bugs.
2. regarding the logging size I agree. there is already debug mode build in the module we need to add the logic should be quick to add would you like us to add a quick fix or add this feature for the next release? please also let us know regarding combining the logs files

2021-03-29 12:24 UTC, zach1988 commented on view/frontend/templates/forter.phtml
> +                $(document).on('change', '<?php echo $elementToObserve; ?>', function(event) {
remove jquery from the module completely and work with query selector will be added to the next version I will let Ziv know that we need to add this to the scope