2.0.31
forter/forter-magento2 pull request #58
Opened 2021-04-22 14:55 UTC by pniel-cohen

* Added PrePost validation option.
* Allow adding custom mappings for `verificationResults` from the module configurations.
* Prevent sending empty `forterTokenCookie`.
* Changes & improvements on logger (changed log name from `response` to `debug`, so it would be more versatile).
* Added forter action/decision to order notes.
* Remove unnecessary custom order columns.

2021-04-22 15:57 UTC, orpolaczek requested changes

2021-04-22 15:57 UTC, orpolaczek commented on Model/Config.php
> +            $message = $prefix . json_encode($message);
What happens if message isn't a JSON/String?

2021-04-22 15:57 UTC, orpolaczek commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
Actually this seems wrong. 
We want the userAgent especially if the forterToken is empty. 

We should change this to only not send the forterToken if it's not there.

2021-04-22 15:57 UTC, orpolaczek commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
We want all the other options too

2021-04-22 15:57 UTC, orpolaczek commented on Model/RequestBuilder/Order.php
> +            "connectionInformation" => $connectionInformation,
For phone orders we indeed only want the webId and no connectionInformation at all

2021-04-22 15:57 UTC, orpolaczek commented on Observer/OrderValidation/PaymentPlaceStart.php
> +            if (!($connectionInformation = $this->basicInfo->getConnectionInformation($order->getRemoteIp() ?: $this->remote->getRemoteAddress()))) {
Can you please make this one more readable?

2021-04-22 15:57 UTC, orpolaczek commented on Observer/OrderValidation/PaymentPlaceStart.php
> +            if (!($connectionInformation = $this->basicInfo->getConnectionInformation($order->getRemoteIp() ?: $this->remote->getRemoteAddress()))) {
It's prune to bugs. Especially assigning a variable as part of the of statement.

2021-04-25 06:41 UTC, pniel-cohen commented on Model/Config.php
> +            $message = $prefix . json_encode($message);
It would become JSON. It's just a protection, so it won't throw errors (practically it will always be a string & the json_encode won't effect it, but is for any reason it would get an array/object, it would be fine).

2021-04-25 06:51 UTC, pniel-cohen commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
I did that in order to prevent cases like CyberSource (when they trigger the same controller from their side at the same time, but they don't have the cookie, so it's causing issues).
Now it should skip those cases (If the  request is missing the cookie, I assume that it's not the customer's browser & might be a side request from the gateway. But I understand why it might be important to you as well).
If you want to get those anyway & still avoid issues on CyberSource, usually I prefer more generic solutions, but it's possible to identify them by their user-agent & then skip (since they will never have the cookie on the requests from their side).

2021-04-25 06:52 UTC, pniel-cohen commented on Model/RequestBuilder/Order.php
> +            "connectionInformation" => $connectionInformation,
I didn't change that, only corrected the tab-spacing on the file.
Do you want to make changes here now or wait for the next release?

2021-04-25 07:01 UTC, pniel-cohen commented on Observer/OrderValidation/PaymentPlaceStart.php
> +            if (!($connectionInformation = $this->basicInfo->getConnectionInformation($order->getRemoteIp() ?: $this->remote->getRemoteAddress()))) {
Please choose one of those & I'll apply.
*A is better IMO, since we don't need the remoteIp later.

**A:**
```
$connectionInformation = $this->basicInfo->getConnectionInformation(
    $order->getRemoteIp() ?: $this->remote->getRemoteAddress()
);
if (!$connectionInformation) {
    return;
}
```
**B:**
```
$remoteIp = $order->getRemoteIp() ?: $this->remote->getRemoteAddress();
$connectionInformation = $this->basicInfo->getConnectionInformation($remoteIp);
if (!$connectionInformation) {
    return;
}
```

2021-04-25 14:05 UTC, orpolaczek commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
We need to check that with the 'token trigger' integration and see what happens. It is possible to not have cookies (disabled cookies in browser, etc).

2021-04-26 05:56 UTC, orpolaczek commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
@dondrich  care to take a deeper look into the code?

2021-04-26 05:56 UTC, orpolaczek commented on Model/RequestBuilder/Order.php
> +            "connectionInformation" => $connectionInformation,
@zivfishfedder  will have the answer

2021-04-26 05:57 UTC, orpolaczek commented on Observer/OrderValidation/PaymentPlaceStart.php
> +            if (!($connectionInformation = $this->basicInfo->getConnectionInformation($order->getRemoteIp() ?: $this->remote->getRemoteAddress()))) {
I agree A is better :)

2021-04-26 07:11 UTC, zivfishfedder commented on Model/RequestBuilder/Order.php
> +            "connectionInformation" => $connectionInformation,
@pniel-cohen - we're still waiting for David's code review for another task and he's in NYC, so if you can update this in the next few hours, please do. i.e. we only want the webId and no connectionInformation.

2021-04-26 10:10 UTC, pniel-cohen commented on Observer/OrderValidation/PaymentPlaceStart.php
> +            if (!($connectionInformation = $this->basicInfo->getConnectionInformation($order->getRemoteIp() ?: $this->remote->getRemoteAddress()))) {
Done.

2021-04-26 10:29 UTC, pniel-cohen commented on Model/RequestBuilder/Order.php
> +            "connectionInformation" => $connectionInformation,
@orpolaczek @zivfishfedder 
Removed the `connectionInformation` on a new commit (+some general conmetics on the same area).
closing this one for now.

2021-04-26 10:29 UTC, pniel-cohen commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
Waiting for decisions.

2021-04-26 13:20 UTC, dondrich commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
@pniel-cohen is there only an issue with CyberSource? Is there a way to identify who's triggering the controller other than the user agent? Sometimes they can be flaky.

Regardless since it is possible to have no token and no cookie we need to find a new solution here.

2021-04-28 09:19 UTC, pniel-cohen commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
@dondrich 
I agree, I also didn't like the idea of relying on the user-agent, but it's possible (not sure if there's another way to identify them, but we noticed that it's pretty solid on the requests from them).
I'm also not aware of issues with other gateways other than CyberSource.
Regarding a non-cookie solution, let's discuss that in more details. If it's possible, that would solve this one (at least).
Note that using a cookie is practically the same as using local-storage or other  session solutions (for this matter), since they all need to store stuff on the client's browser.

2021-04-28 11:52 UTC, dondrich commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
@pniel-cohen I don't know if this will work, but is it possible to name the function something different that CyberSource (or any other gateway) won't call?

2021-05-02 07:27 UTC, pniel-cohen commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
@dondrich 
It's not possible, because they are calling a controller that calls the standard Magento flow for placing orders. The module only rides on top of it, as a plugin & does what it does.

2021-05-03 14:23 UTC, pniel-cohen commented on Model/RequestBuilder/BasicInfo.php
> +        if ($forterToken) {
Applied a different fix as agreed.
*Allow empty forterToken cookie, but skip CyberSource by user-agent detection.
Waiting for QA results, closing this conversation for now since this code has been changed.

2021-05-04 16:06 UTC, merged